# Generated by Django 4.0.5 on 2022-06-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Genero')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Nombre de Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Tamanio',
            fields=[
                ('idTamanio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Tamaño')),
                ('nombreTamanio', models.CharField(max_length=50, verbose_name='Nombre de Tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('precio', models.CharField(max_length=11, verbose_name='Precio')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('tamanio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tamanio', verbose_name='Tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=65, verbose_name='Direccion')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero', verbose_name='Genero')),
            ],
        ),
    ]
